name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact_name:
        description: The name of the artifact
        required: true
        type: string
    secrets:
      PETS_NAME:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}
      - name: Output contents
        run: ls
      - name: Deploy
        run: |
          echo "Deploying... using reusable code"
          echo "${{ secrets.PETS_NAME }}"
