name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact_name:
        description: The name of the artifact
        required: true
        type: string
      environment:
        description: The name of the environment
        required: true
        type: string
    secrets:
      PETS_NAME:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}
      - name: Output contents
        run: ls
      - name: Deploy
        run: |
          echo "${{ secrets.PETS_NAME }}"
          echo "Deploying... using reusable code"
  debug_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secret Value
        run: |
          echo "Secret value: ${{ secrets.PETS_NAME }}"
      - name: Write Secret Value to File
        run: |
          echo "${{ secrets.PETS_NAME }}" > secret_value.txt
        # Write the secret value to a file named "secret_value.txt"
      - name: Upload File as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: secret-value
          path: secret_value.txt
